language: node_js
notifications:
  email: false
node_js:
  - "12"
  - "11"
  - "10"
before_install: sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
install: npm install
jobs:
  include:
    - stage: test
      script: npm test
cache:
  directories:
    - node_modules